name: ReShaper-InspectCode

on:
  push:
    branches:
      - master
      - dev
      - 'releases/*'
  pull_request:
    types: [ opened, reopened ]
  workflow_dispatch:

jobs:
  inspect-code:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Annotate
        # You may pin to the exact commit or the version.
        uses: JetBrains/ReSharper-InspectCode@v0.3
        with:
          solution: ./Fork.sln
          tool-version: 2023.3.2
          exclude: packages/*
          sEverity: ERROR

    permissions:
      security-events: write